### ISSUE TITLE
Strategy: Find the Total Average Budget in Survey

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/food-doods#10]
How much are people spending total per month?

**Comment by sandyklc** [comment]
This is also done! All data synthesis from the survey is under the data here:https://docs.google.com/spreadsheets/d/1QdAzAtsep46K2YASdRSGVayzMBoYnhiaqp7NEbN8RdU/edit?usp=drive_web&ouid=103519807203062357237

(Data synthesis of survey data was done by Sang)
