### ISSUE TITLE
Strategy: Compiling Data into Personas

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/food-doods#11]
What are the common trends you see in our survey data? Do they fit into archetypes? Please record your findings in the W2 folder.

Quantity is better, we will investigate this together at our next meeting.

**Comment by sandyklc** [comment]
Interview data is synthesized: https://docs.google.com/spreadsheets/d/1hr8ukwP5AmLqI9UjcWzRFl7tAcYlP1ytBUEtErVdM7E/edit#gid=0

Persona created: https://docs.google.com/document/d/1RoEfW1FNHypEGQHab8VsfALvLH33ap6TvW7pa1dH_sE/edit

Created by Design & Strategy team: Sandy, Jess & Sang
