### ISSUE TITLE
Strategy: Compiling Personas into User Stories

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/food-doods#12]
How can we take our personas and generate our set of user stories? Do these people interact with the application in a specific way?

As <persona>, I want <a feature or ability within the app>, so that I can <a benefit of using the app>

Please record your findings in the W2 folder of the drive.

Quantity is better, we will investigate this together at our next meeting.

**Comment by sandyklc** [comment]
Link for user stories: https://docs.google.com/spreadsheets/d/1oFsLztqGcrIf833PN8rQcT_rd6ndNMZUW0ih6BB1udE/edit#gid=0
