### ISSUE TITLE
Create Test Users

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/food-doods#139]
Create 3 test users in prod DB and add a set ~10 ingredients to each

LIst here

**Comment by aviquez96** [comment]
The users have been added and connected with ingredients.

The List is provided below:

**User Id’s**
Mongo —> Ingredient Service
5e7d5b4b3ea52245ea87faed —> 11
5e7fc84f9227110e73460065 —> 12 
5e7d58ecba49051abeb5e097 —> 13

**Ingredient Id’s**
Beef: 23553
Corn: 23554
Beans: 23555
Basil: 23556
Garlic: 23557
Onion: 23558
Cucumber: 23559
Cheese: 23560
Rice: 23561
Salad: 23562
Apple: 23563
Cinammon: 23564
Pepper: 23565

**Sample User with Ingredients**
![Screen Shot 2020-03-28 at 4 20 56 PM](https://user-images.githubusercontent.com/25270088/77836072-22791f00-7110-11ea-982a-cd21cdb42a7a.png)

**Comment by DConnorFong** [comment]
@wrenliang @yan-alan we can now use these
