### ISSUE TITLE
Suggestion GET Recipes 

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/food-doods#142]
Service should get a set of recipes from Recipe Service

**Comment by DConnorFong** [comment]
See L133 in routes

**Comment by andrewzulaybar** [comment]
> See L133 in routes

@DConnorFong Can you clarify what you mean here? I can't find a line 133 anywhere :(

**Comment by aviquez96** [comment]
> > See L133 in routes
> 
> @DConnorFong Can you clarify what you mean here? I can't find a line 133 anywhere :(

> I think he meant line 33 in the suggestion.ts file

**Comment by DConnorFong** [comment]
@andrewzulaybar line 33 yup my mistake :(
