### ISSUE TITLE
Ingredient: Populate Database

### ISSUE THREAD

**Issue by narendrasss** [ubclaunchpad/food-doods#52]
Use the Edamam API as outlined in the [google doc](https://docs.google.com/document/d/1CsNoUQJHvT4BGUfDP13E3D5P4ZjAbdSZrTQEAtGFVKY/edit?usp=sharing) to populate the internal `ingredient` table.

Alternatively, lazily populates the database as users add ingredients to their fridge. In this case, the search functionality should go through the Edamam API.

@DConnorFong

**Comment by DConnorFong** [comment]
Can you focus on the implementation this week? Ideally util methods that will handle these calls

**Comment by narendrasss** [comment]
@DConnorFong Sure yeah. This week's a pretty busy week for me, but I'll try to get as much done.
