### ISSUE TITLE
Strategy: Fix Part-Time Option in Survey

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/food-doods#9]
Please gather data on the part time-option after removing full-time employees.

**Comment by sandyklc** [comment]
Data Synthesis is done: https://docs.google.com/spreadsheets/d/1QdAzAtsep46K2YASdRSGVayzMBoYnhiaqp7NEbN8RdU/edit?usp=drive_web&ouid=103519807203062357237
